theme:
  - hugo-theme-stack
  - almeida-cv

enableRobotsTXT: true
enableEmoji: true

params:
  enableMetaTags: true
  colorLight: "#fff"
  colorDark: "#666"
  colorPageBackground: "#ddd"
  colorPrimary: "#e3bfb8"
  colorSecondary: "#aaa"
  colorIconPrimary: "#fff"
  colorIconBackground: "#e3bfb8"
  colorRightColumnBackground: "#f5f5f5"
  colorRightColumnHeadingText: "#666"
  colorRightColumnBodyText: "#666"
  colorRightColumnIconPrimary: "#fff"
  colorRightColumnIconBackground: "#e3bfb8"
  pages: 1
  swapColumns: true
